name: Hangman Frontend CD

on:
    workflow_dispatch:  # Permite la ejecución manual del workflow
  
jobs:
    build-and-push:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository # Obtener el código del repositorio
          uses: actions/checkout@v4

        - name: Login to GitHub Container Registry # Autenticación en el GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ github.repository }}:latest
              ghcr.io/${{ github.repository }}:${{ github.sha }}
      
